language: ruby
notifications:
  email:
    recipients:
      - mike@just3ws.com
rvm:
  - 2.4.0
cache: bundler
sudo: false
install: ./.travis/install
script:
  - bundle exec rspec
  - bundle exec codeclimate-test-reporter
addons:
  code_climate:
    repo_token:
      secure: "tA9YT9z7nHWeB//TFmBAn595ahsjnm8esP5/6zcrPjkBx661hnpgxMLF9uZT7SFuE31x1G6pA0Jcc77lN3X2ii/fNTxoNeQR9uwyqxCMhuxk01R/hwiHQMITUWL5I7eTa9yFItHf+DBDJuLiepQPVHbS0LjQ6++vP4whEFTWF+RTQNL+JEEe3wM/9G6X5iASP9khDXrlfpjOeryx15I7f2qQp4cc1rsO06B1KCDpjmLjXUBsVfwh2ZZ/clW8FLViffFMEHGy21K2/BX3a1tcevB2cksyTw0ZT/sdv4TcJzPXJkibaeUjMKDlOvT4NPyiSIf62TO30Ohk/M6k6vH+ctJBQxESYrLXLVvfxKiO5C8XuDh9GlgWyku1Ed5SRYG0dV8Fbo2buZvZZBTbz7twfp7C9zgHzqFHI+kSg+VuHNs99JklJLv7kcLQy3YBfgjO+IwAZkcjkCpdMxr/sFr+Z/bIWu+IOuDtApa0PVqoWSNYfczGzZlh3bz7AQ7wsywfbtfnG5/Ws8ZCD6eykgoMOPc91BneR4Mj1s/AeQksz2jylNxbuURB073mANRHdVzCptV+zcCfwYdjGTjkW3SMLTAIomgU2jWLwiKnxF7s6As2/l2nke54w7NX3U+WZk4IWf4BCKdoOmEeJiKolla/JscJMnpKpgBw5y52iLhEcYk="
