# encoding: utf-8
# frozen_string_literal: true
Card.new(type: :ace, token: 'AC', suit: :clubs, card_character: '🂡', suit_character: '♣')
Card.new(type: :ace, token: 'AC', suit: :diamonds, card_character: '🃁', suit_character: '♦')
Card.new(type: :ace, token: 'AC', suit: :hearts, card_character: '🂱', suit_character: '♥')
Card.new(type: :ace, token: 'AC', suit: :spades, card_character: '🃑', suit_character: '♠')
Card.new(type: :eight, token: '08', suit: :clubs, card_character: '🂨', suit_character: '♣')
Card.new(type: :eight, token: '08', suit: :diamonds, card_character: '🃈', suit_character: '♦')
Card.new(type: :eight, token: '08', suit: :hearts, card_character: '🂸', suit_character: '♥')
Card.new(type: :eight, token: '08', suit: :spades, card_character: '🃘', suit_character: '♠')
Card.new(type: :five, token: '05', suit: :clubs, card_character: '🂥', suit_character: '♣')
Card.new(type: :five, token: '05', suit: :diamonds, card_character: '🃅', suit_character: '♦')
Card.new(type: :five, token: '05', suit: :hearts, card_character: '🂵', suit_character: '♥')
Card.new(type: :five, token: '05', suit: :spades, card_character: '🃕', suit_character: '♠')
Card.new(type: :four, token: '04', suit: :clubs, card_character: '🂤', suit_character: '♣')
Card.new(type: :four, token: '04', suit: :diamonds, card_character: '🃄', suit_character: '♦')
Card.new(type: :four, token: '04', suit: :hearts, card_character: '🂴', suit_character: '♥')
Card.new(type: :four, token: '04', suit: :spades, card_character: '🃔', suit_character: '♠')
Card.new(type: :jack, token: '10', suit: :clubs, card_character: '🂫', suit_character: '♣')
Card.new(type: :jack, token: '10', suit: :diamonds, card_character: '🃋', suit_character: '♦')
Card.new(type: :jack, token: '10', suit: :hearts, card_character: '🂻', suit_character: '♥')
Card.new(type: :jack, token: '10', suit: :spades, card_character: '🃛', suit_character: '♠')
Card.new(type: :king, token: '10', suit: :clubs, card_character: '🂮', suit_character: '♣')
Card.new(type: :king, token: '10', suit: :diamonds, card_character: '🃎', suit_character: '♦')
Card.new(type: :king, token: '10', suit: :hearts, card_character: '🂾', suit_character: '♥')
Card.new(type: :king, token: '10', suit: :spades, card_character: '🃞', suit_character: '♠')
Card.new(type: :nine, token: '09', suit: :clubs, card_character: '🂩', suit_character: '♣')
Card.new(type: :nine, token: '09', suit: :diamonds, card_character: '🃉', suit_character: '♦')
Card.new(type: :nine, token: '09', suit: :hearts, card_character: '🂹', suit_character: '♥')
Card.new(type: :nine, token: '09', suit: :spades, card_character: '🃙', suit_character: '♠')
Card.new(type: :queen, token: '10', suit: :clubs, card_character: '🂭', suit_character: '♣')
Card.new(type: :queen, token: '10', suit: :diamonds, card_character: '🃍', suit_character: '♦')
Card.new(type: :queen, token: '10', suit: :hearts, card_character: '🂽', suit_character: '♥')
Card.new(type: :queen, token: '10', suit: :spades, card_character: '🃝', suit_character: '♠')
Card.new(type: :seven, token: '07', suit: :clubs, card_character: '🂧', suit_character: '♣')
Card.new(type: :seven, token: '07', suit: :diamonds, card_character: '🃇', suit_character: '♦')
Card.new(type: :seven, token: '07', suit: :hearts, card_character: '🂷', suit_character: '♥')
Card.new(type: :seven, token: '07', suit: :spades, card_character: '🃗', suit_character: '♠')
Card.new(type: :six, token: '06', suit: :clubs, card_character: '🂦', suit_character: '♣')
Card.new(type: :six, token: '06', suit: :diamonds, card_character: '🃆', suit_character: '♦')
Card.new(type: :six, token: '06', suit: :hearts, card_character: '🂶', suit_character: '♥')
Card.new(type: :six, token: '06', suit: :spades, card_character: '🃖', suit_character: '♠')
Card.new(type: :ten, token: '10', suit: :clubs, card_character: '🂪', suit_character: '♣')
Card.new(type: :ten, token: '10', suit: :diamonds, card_character: '🃊', suit_character: '♦')
Card.new(type: :ten, token: '10', suit: :hearts, card_character: '🂺', suit_character: '♥')
Card.new(type: :ten, token: '10', suit: :spades, card_character: '🃚', suit_character: '♠')
Card.new(type: :three, token: '03', suit: :clubs, card_character: '🂣', suit_character: '♣')
Card.new(type: :three, token: '03', suit: :diamonds, card_character: '🃃', suit_character: '♦')
Card.new(type: :three, token: '03', suit: :hearts, card_character: '🂳', suit_character: '♥')
Card.new(type: :three, token: '03', suit: :spades, card_character: '🃓', suit_character: '♠')
Card.new(type: :two, token: '02', suit: :clubs, card_character: '🂢', suit_character: '♣')
Card.new(type: :two, token: '02', suit: :diamonds, card_character: '🃂', suit_character: '♦')
Card.new(type: :two, token: '02', suit: :hearts, card_character: '🂲', suit_character: '♥')
Card.new(type: :two, token: '02', suit: :spades, card_character: '🃒', suit_character: '♠')
