#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
set -vx

rm -f Gemfile Gemfile.lock .rspec
cp -f ./.travis/Gemfile .
cp -f ./.travis/.rspec .
gem update --system
gem install bundler
bundle install --jobs=3 --retry=3
